[variables]

[variables.reco_edep]
key = "reco_edep"
range = [0.0, 4.0]
nbins = 50
xlabel = "Reconstructed Visible Energy"

[variables.true_edep]
key = "true_edep"
range = [0.0, 4.0]
nbins = 50
xlabel = "True Energy"

[variables.true_edep_eff]
key = "true_edep"
range = [0.0, 4.0]
nbins = 50
binning_scheme = "equal_population"
xlabel = "True Energy"

[variables.category_reco]
key = "category_reco"
range = [0, 8]
nbins = 8
xlabel = "Reconstructed Category"

[variables.category_true]
key = "category"
range = [0, 8]
nbins = 8
xlabel = "True Category"

[variables.leading_shower_energy_reco]
key = "leading_shower_energy_reco"
range = [0, 8000]
nbins = 80
xlabel = "Reconstructed Leading Shower Energy"

[variables.leading_shower_energy_true]
key = "leading_shower_energy"
range = [0, 8000]
nbins = 80
xlabel = "True Leading Shower Energy"

[variables.subleading_shower_energy_reco]
key = "subleading_shower_energy_reco"
range = [0, 8000]
nbins = 80
xlabel = "Reconstructed Subleading Shower Energy"

[variables.subleading_shower_energy_true]
key = "subleading_shower_energy"
range = [0, 8000]
nbins = 80
xlabel = "True Subleading Shower Energy"

[variables.leading_electron_primary_softmax]
key = "leading_electron_primary_softmax"
range = [0, 1]
nbins = 50
xlabel = "Leading Electron Primary Softmax Score"

[variables.leading_electron_electron_softmax]
key = "leading_electron_electron_softmax"
range = [0, 1]
nbins = 50
xlabel = "Leading Electron Electron Softmax Score"

[variables.leading_electron_photon_softmax]
key = "leading_electron_photon_softmax"
range = [0, 1]
nbins = 50
xlabel = "Leading Electron Photon Softmax Score"

[variables.subleading_electron_primary_softmax]
key = "subleading_electron_primary_softmax"
range = [0, 1]
nbins = 50
xlabel = "Subleading Electron Primary Softmax Score"

[variables.subleading_electron_electron_softmax]
key = "subleading_electron_electron_softmax"
range = [0, 1]
nbins = 50
xlabel = "Subleading Electron Electron Softmax Score"

[variables.subleading_electron_photon_softmax]
key = "subleading_electron_photon_softmax"
range = [0, 1]
nbins = 50
xlabel = "Subleading Electron Photon Softmax Score"

[variables.invariant_mass]
key = "invariant_mass"
range = [0, 3000]
nbins = 50
xlabel = "Reco Invariant Mass"

[variables.invariant_mass_true]
key = "invariant_mass_true"
range = [0, 3000]
nbins = 50
xlabel = "True Invariant Mass"

[variables.energy_asymmetry_reco]
key = "energy_asymmetry"
range = [0.0, 1.0]
nbins = 50
xlabel = "Reconstructed Energy Asymmetry"

[variables.energy_asymmetry_true]
key = "energy_asymmetry_true"
range = [0.0, 1.0]
nbins = 50
xlabel = "True Energy Asymmetry"

[variables.opening_angle]
key = "opening_angle"
range = [-1, 1]
nbins = 50
xlabel = "True Opening Angle"

[variables.true_opening_angle]
key = "true_opening_angle"
range = [-1, 1]
nbins = 30
binning_scheme = "equal_population"
xlabel = "True Opening Angle"

[variables.opening_angle_reco]
key = "opening_angle_reco"
range = [-1, 1]
nbins = 50
xlabel = "Reco Opening Angle"

[variables.nshowers]
key = "nshowers"
range = [0, 10]
nbins = 10
xlabel = "Number of Reconstructed Showers"

[variables.nphotons]
key = "nphotons"
range = [0, 10]
nbins = 10
xlabel = "Number of Reconstructed Photons"

[variables.IoU]
key = "IoU"
range = [0.0, 1.0]
nbins = 30
xlabel = "IoU"

[variables.true_vertex_x]
key = "true_vertex_x"
range = [-400, 400]
nbins = 200
xlabel = "True Vertex X Position"

[variables.reco_vertex_x]
key = "reco_vertex_x"
range = [-400, 400]
nbins = 200
xlabel = "Reconstructed Vertex X Position"

[variables.true_vertex_y]
key = "true_vertex_y"
range = [-300, 300]
nbins = 200
xlabel = "True Vertex Y Position"

[variables.reco_vertex_y]
key = "reco_vertex_y"
range = [-300, 300]
nbins = 200
xlabel = "Reconstructed Vertex Y Position"

[variables.true_vertex_z]
key = "true_vertex_z"
range = [-900, 900]
nbins = 600
xlabel = "True Vertex Z Position"

[variables.reco_vertex_z]
key = "reco_vertex_z"
range = [-900, 900]
nbins = 600
xlabel = "Reconstructed Vertex Z Position"

[variables.true_vertex_distance]
key = "true_vertex_distance"
range = [0, 5]
nbins = 50
xlabel = "True Max Vertex Distance"

[variables.reco_vertex_distance]
key = "reco_vertex_distance"
range = [0, 100]
nbins = 75
xlabel = "Reconstructed Max Vertex Distance"

[variables.nelectrons]
key = "nelectrons"
range = [0, 10]
nbins = 10
xlabel = "Number of Reconstructed Electrons"